#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Oct 29 01:48:35 2022

@author: tavo
"""

import numpy as np
import pandas as pd

###############################################################################
# Auxiliary functions
###############################################################################
'''
CITEKmers = pd.read_csv('/media/tavo/storage/0openproblems/data/seqs/CITETrainKmersA.csv')
CITEKmers = CITEKmers.set_index('ids')

foldsIndexCITE = pd.read_csv('/media/tavo/storage/0openproblems/data/seqs/CITETrainFolds.csv')

BasePathCITE = '/media/tavo/storage/0openproblems/archive/CITE'

trainInputsDirCITE = BasePathCITE + '/train-inputs'

batchsize = 200
foldmins = []
foldmaxs = []

for col in foldsIndexCITE.columns:
    print(col)
    foldnames = foldsIndexCITE[col].tolist()
    innermins = []
    innermaxs = []
    for k in range(0,len(foldnames)-batchsize,batchsize):
        names = foldnames[k:k+batchsize]
        container = []
        for val in names:
            container.append(np.load(trainInputsDirCITE+'/'+val+'.npy'))
        container = np.array(container)
        container = np.hstack((container,np.array(CITEKmers.loc[names])))
        
        innermins.append(container.min(axis=0))
        innermaxs.append(container.max(axis=0))
            
    innermins = np.array(innermins)
    innermaxs = np.array(innermaxs)
    foldmins.append(innermins.min(axis=0))
    foldmaxs.append(innermaxs.max(axis=0))

foldMinsDF = pd.DataFrame()
foldMaxsDF = pd.DataFrame()

for k,val in enumerate(foldsIndexCITE.columns):
    foldMinsDF[val] = foldmins[k]
    foldMaxsDF[val] = foldmaxs[k]

foldMinsDF.to_csv('/media/tavo/storage/0openproblems/data/seqs/CITEMinsFolds.csv',index=False)
foldMaxsDF.to_csv('/media/tavo/storage/0openproblems/data/seqs/CITEMaxsFolds.csv',index=False)
'''
###############################################################################
# Auxiliary functions
###############################################################################

foldsIndexMULTI = pd.read_csv('/media/tavo/storage/0openproblems/data/seqs/MULTITrainFolds.csv')

trainXKmerspath ='/media/tavo/storage/0openproblems/data/seqs/MULTITrainKmersA.csv'
trainXFeatspath ='/media/tavo/storage/0openproblems/data/seqs/MULTITrainFeats.csv'

trainXKmerData = pd.read_csv(trainXKmerspath)
trainXKmerData = trainXKmerData.set_index('ids')

trainXFeatData = pd.read_csv(trainXFeatspath)
trainXFeatData = trainXFeatData.set_index('ids')

trainXData = pd.concat([trainXKmerData,trainXFeatData],axis=1)

minsMulti = []
maxsMulti = []

for col in foldsIndexMULTI.columns:
    colvals = foldsIndexMULTI[col].tolist()
    minsMulti.append(trainXData.loc[colvals].min(axis=0))
    maxsMulti.append(trainXData.loc[colvals].max(axis=0))

foldMinsMULTIDF = pd.DataFrame()
foldMaxsMULTIDF = pd.DataFrame()

for k,val in enumerate(foldsIndexMULTI.columns):
    foldMinsMULTIDF[val] = minsMulti[k]
    foldMaxsMULTIDF[val] = maxsMulti[k]

foldMinsMULTIDF.to_csv('/media/tavo/storage/0openproblems/data/seqs/MULTIMinsFolds.csv',index=False)
foldMaxsMULTIDF.to_csv('/media/tavo/storage/0openproblems/data/seqs/MULTIMaxsFolds.csv',index=False)

